import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Kidz Joy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <header className="bg-primary">
          <Navbar />
        </header>
        <main className="flex-1 max-w-7xl mx-auto">{children}</main>

        <footer className="bg-primary">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
